import type { NewCustomListingField } from "../schema.ts";

type SeedCustomListingField = Pick<
  NewCustomListingField,
  | "category"
  | "description"
  | "fieldType"
  | "helpText"
  | "isFilterable"
  | "isPublic"
  | "isRequired"
  | "key"
  | "label"
  | "options"
  | "placeholder"
  | "sortOrder"
>;

export const customListingFieldSeed = [
  {
    key: "main_entrance_is_barrier_free",
    label: "Main Entrance is Barrier-Free",
    description: null,
    fieldType: "boolean",
    category: "ENTRY & EXTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 1,
    options: null,
  },
  {
    key: "accessible_tenant_parking_available",
    label: "Accessible Tenant Parking Available",
    description: null,
    fieldType: "boolean",
    category: "ENTRY & EXTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 2,
    options: null,
  },
  {
    key: "on_site_parking",
    label: "On-Site Parking",
    description: null,
    fieldType: "boolean",
    category: "ENTRY & EXTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 3,
    options: null,
  },
  {
    key: "accessible_guest_parking",
    label: "Accessible Guest Parking",
    description: null,
    fieldType: "boolean",
    category: "ENTRY & EXTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 4,
    options: null,
  },
  {
    key: "proximity_to_bus_transit",
    label: "Proximity to Bus/Transit",
    description: null,
    fieldType: "boolean",
    category: "ENTRY & EXTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 5,
    options: null,
  },
  {
    key: "good_pedestrian_access",
    label: "Good Pedestrian Access",
    description: null,
    fieldType: "boolean",
    category: "ENTRY & EXTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 6,
    options: null,
  },
  {
    key: "elevator_in_building",
    label: "Elevator in Building",
    description: null,
    fieldType: "boolean",
    category: "BUILDING AMENITIES",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 7,
    options: null,
  },
  {
    key: "cellphone_elevator_control",
    label: "Cellphone Elevator Control",
    description: null,
    fieldType: "boolean",
    category: "BUILDING AMENITIES",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 8,
    options: null,
  },
  {
    key: "accessible_shared_laundry",
    label: "Accessible Shared Laundry",
    description: null,
    fieldType: "boolean",
    category: "BUILDING AMENITIES",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 9,
    options: null,
  },
  {
    key: "braille_signage",
    label: "Braille Signage",
    description: null,
    fieldType: "boolean",
    category: "BUILDING AMENITIES",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 10,
    options: null,
  },
  {
    key: "tactile_cues_textures_domes",
    label: "Tactile Cues (Textures/Domes)",
    description: null,
    fieldType: "boolean",
    category: "BUILDING AMENITIES",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 11,
    options: null,
  },
  {
    key: "lowered_mailboxes",
    label: "Lowered Mailboxes",
    description: null,
    fieldType: "boolean",
    category: "BUILDING AMENITIES",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 12,
    options: null,
  },
  {
    key: "accessible_guest_intercom",
    label: "Accessible Guest Intercom",
    description: null,
    fieldType: "boolean",
    category: "BUILDING AMENITIES",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 13,
    options: null,
  },
  {
    key: "automated_building_doors",
    label: "Automated Building Doors",
    description: null,
    fieldType: "boolean",
    category: "BUILDING AMENITIES",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 14,
    options: null,
  },
  {
    key: "unit_entrance_is_barrier_free",
    label: "Unit Entrance is Barrier-Free",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 15,
    options: null,
  },
  {
    key: "ceiling_lift_ready",
    label: "Ceiling Lift Ready",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 16,
    options: null,
  },
  {
    key: "automated_unit_doors",
    label: "Automated Unit Doors",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 17,
    options: null,
  },
  {
    key: "no_stairs_within_unit",
    label: "No Stairs Within Unit",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 18,
    options: null,
  },
  {
    key: "wide_doorways",
    label: "Wide Doorways",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 19,
    options: null,
  },
  {
    key: "lever_door_handles",
    label: "Lever Door Handles",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 20,
    options: null,
  },
  {
    key: "lowered_light_switches",
    label: "Lowered Light Switches",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 21,
    options: null,
  },
  {
    key: "hard_flooring",
    label: "Hard Flooring",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 22,
    options: null,
  },
  {
    key: "carpeted_floors",
    label: "Carpeted Floors",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 23,
    options: null,
  },
  {
    key: "air_conditioning",
    label: "Air Conditioning",
    description: null,
    fieldType: "boolean",
    category: "UNIT INTERIOR",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 24,
    options: null,
  },
  {
    key: "lowered_kitchen_counters",
    label: "Lowered Kitchen Counters",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 25,
    options: null,
  },
  {
    key: "lowered_cabinets",
    label: "Lowered Cabinets",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 26,
    options: null,
  },
  {
    key: "front_stove_controls",
    label: "Front Stove Controls",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 27,
    options: null,
  },
  {
    key: "convection_cooktop",
    label: "Convection Cooktop",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 28,
    options: null,
  },
  {
    key: "front_dishwasher_controls",
    label: "Front Dishwasher Controls",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 29,
    options: null,
  },
  {
    key: "bottom_door_freezer",
    label: "Bottom-Door Freezer",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 30,
    options: null,
  },
  {
    key: "non_digital_appliances",
    label: "Non-Digital Appliances",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 31,
    options: null,
  },
  {
    key: "barrier_free_bathroom",
    label: "Barrier-Free Bathroom",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 32,
    options: null,
  },
  {
    key: "lowered_bathroom_counters",
    label: "Lowered Bathroom Counters",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 33,
    options: null,
  },
  {
    key: "accessible_height_toilet",
    label: "Accessible Height Toilet",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 34,
    options: null,
  },
  {
    key: "roll_in_shower",
    label: "Roll-In Shower",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 35,
    options: null,
  },
  {
    key: "walk_in_shower",
    label: "Walk-In Shower",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 36,
    options: null,
  },
  {
    key: "grab_bars_general",
    label: "Grab Bars (General)",
    description: null,
    fieldType: "boolean",
    category: "KITCHEN & BATH",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 37,
    options: null,
  },
  {
    key: "smoke_co_detectors_w_strobe",
    label: "Smoke & CO Detectors w/ Strobe",
    description: null,
    fieldType: "boolean",
    category: "SAFETY & SENSORY",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 38,
    options: null,
  },
  {
    key: "sprinkler_system",
    label: "Sprinkler System",
    description: null,
    fieldType: "boolean",
    category: "SAFETY & SENSORY",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 39,
    options: null,
  },
  {
    key: "service_animals_allowed",
    label: "Service Animals Allowed",
    description: null,
    fieldType: "boolean",
    category: "SAFETY & SENSORY",
    helpText: null,
    placeholder: null,
    isPublic: true,
    isFilterable: true,
    isRequired: false,
    sortOrder: 40,
    options: null,
  },
] satisfies SeedCustomListingField[];
